---
title: Centre for Development Results
timezone: America/New_York
permalink: "/:title"
collections:
  news:
    title: News
    output: true
    permalink: "/news/:title"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  members:
    title: members
    output: false
defaults:
- scope:
    path: ''
    type: members
  values:
    summary:
    logo-image: '200x200'
hilighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
email: your-email@domain.com
exclude:
- ".gitignore"
description: |
  Site for the Centre for Development Results
baseurl:
destination: "./build"
sass:
  style: compressed
