---
title: Siteleaf/Jekyll
url: http://siteleaf-jekyll.siteleaf.net
timezone: America/New_York
collections:
  uploads:
    title: Uploads
    output: true
hilighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
email: your-email@domain.com
exclude:
- ".gitignore"
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
destination: "./build"
sass:
  style: compressed
