---
title: Siteleaf/Jekyll
url: http://siteleaf-jekyll.siteleaf.net
timezone: America/New_York
collections:
  news:
    title: News
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  members:
    title: members
    output: false
defaults:
- scope:
    path:
      type: members
  values:
    summary:
    logo-image: '200x200'
gems:
- jekyll-paginate
paginate: 3
paginate_path: "/page:num/"
hilighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
email: your-email@domain.com
exclude:
- ".gitignore"
description: |
  Site for the Centre for Development Results
baseurl:
destination: "./build"
sass:
  style: compressed
